// Lada (NIR) → ciudad principal y estado. Generado el 18-sep-2026 a partir del listado
// de ladas por localidad (gist charecktowa, basado en el Plan de Numeración del IFT),
// eligiendo la localidad más poblada de cada lada (GeoNames). La lada indica dónde se
// dio de alta el número, no necesariamente dónde vive hoy la persona.
const LADAS: Record<string, [string, string]> = {
  "33": ["Guadalajara", "Jalisco"],
  "55": ["Ciudad de México", "CDMX"],
  "56": ["Ciudad de México", "CDMX"],
  "81": ["Monterrey", "Nuevo León"],
  "222": ["Puebla", "Puebla"],
  "223": ["Tepeaca", "Puebla"],
  "224": ["Tochtepec", "Puebla"],
  "225": ["Tlapacoyan", "Veracruz"],
  "226": ["Altotonga", "Veracruz"],
  "227": ["Huejotzingo", "Puebla"],
  "228": ["Jalapa", "Veracruz"],
  "229": ["Veracruz", "Veracruz"],
  "231": ["Teziutlán", "Puebla"],
  "232": ["Martínez de la Torre", "Veracruz"],
  "233": ["Zaragoza", "Puebla"],
  "235": ["Misantla", "Veracruz"],
  "236": ["Ajalpan", "Puebla"],
  "237": ["San Gabriel Chilac", "Puebla"],
  "238": ["Tehuacán", "Puebla"],
  "241": ["Apizaco", "Tlaxcala"],
  "243": ["Izúcar de Matamoros", "Puebla"],
  "244": ["Atlixco", "Puebla"],
  "245": ["Ciudad Serdán", "Puebla"],
  "246": ["Tlaxcala", "Tlaxcala"],
  "247": ["Huamantla", "Tlaxcala"],
  "248": ["San Martín Texmelucan de Labastida", "Puebla"],
  "249": ["Tecamachalco", "Puebla"],
  "271": ["Córdoba", "Veracruz"],
  "272": ["Orizaba", "Veracruz"],
  "273": ["Huatusco", "Veracruz"],
  "274": ["Tierra Blanca", "Veracruz"],
  "275": ["Chiautla de Tapia", "Puebla"],
  "276": ["Libres", "Puebla"],
  "278": ["Cuitláhuac", "Veracruz"],
  "279": ["Alto Lucero", "Veracruz"],
  "281": ["Loma Bonita", "Oaxaca"],
  "282": ["Perote", "Veracruz"],
  "283": ["Isla", "Veracruz"],
  "284": ["Lerdo de Tejada", "Veracruz"],
  "285": ["Soledad de Doblado", "Veracruz"],
  "287": ["Tuxtepec", "Oaxaca"],
  "288": ["Cosamaloapan", "Veracruz"],
  "294": ["San Andrés Tuxtla", "Veracruz"],
  "296": ["José Cardel", "Veracruz"],
  "297": ["Alvarado", "Veracruz"],
  "311": ["Tepic", "Nayarit"],
  "312": ["Colima", "Colima"],
  "313": ["Tecomán", "Colima"],
  "314": ["Manzanillo", "Colima"],
  "315": ["Cihuatlán", "Jalisco"],
  "316": ["Unión de Tula", "Jalisco"],
  "317": ["Autlán", "Jalisco"],
  "319": ["Tuxpan", "Nayarit"],
  "321": ["El Grullo", "Jalisco"],
  "322": ["Puerto Vallarta", "Jalisco"],
  "323": ["Santiago Ixcuintla", "Nayarit"],
  "324": ["Ixtlán del Río", "Nayarit"],
  "325": ["Acaponeta", "Nayarit"],
  "326": ["Zacoalco", "Jalisco"],
  "327": ["Compostela", "Nayarit"],
  "328": ["Vista Hermosa", "Michoacán"],
  "329": ["San José del Valle", "Nayarit"],
  "341": ["Ciudad Guzmán", "Jalisco"],
  "342": ["Sayula", "Jalisco"],
  "343": ["Juanacatlán", "Jalisco"],
  "344": ["Yahualica", "Jalisco"],
  "345": ["Ayotlán", "Jalisco"],
  "346": ["Teocaltiche", "Jalisco"],
  "347": ["San Miguel El Alto", "Jalisco"],
  "348": ["Arandas", "Jalisco"],
  "349": ["Tecolotlán", "Jalisco"],
  "351": ["Zamora", "Michoacán"],
  "352": ["La Piedad", "Michoacán"],
  "353": ["Sahuayo", "Michoacán"],
  "354": ["Los Reyes", "Michoacán"],
  "355": ["Tangancícuaro", "Michoacán"],
  "356": ["Yurécuaro", "Michoacán"],
  "357": ["Casimiro Castillo", "Jalisco"],
  "358": ["Vista Hermosa", "Jalisco"],
  "359": ["Penjamillo", "Michoacán"],
  "371": ["Tuxpan", "Jalisco"],
  "372": ["Atoyac", "Jalisco"],
  "373": ["Zapotlanejo", "Jalisco"],
  "374": ["Tequila", "Jalisco"],
  "375": ["Ameca", "Jalisco"],
  "376": ["Chapala", "Jalisco"],
  "377": ["Cocula", "Jalisco"],
  "378": ["Tepatitlan de Morelos", "Jalisco"],
  "381": ["San José de Gracia", "Michoacán"],
  "382": ["Mazamitla", "Jalisco"],
  "383": ["Santiago Tangamandapio", "Michoacán"],
  "384": ["Tala", "Jalisco"],
  "385": ["San Martín Hidalgo", "Jalisco"],
  "386": ["Magdalena", "Jalisco"],
  "387": ["Jocotepec", "Jalisco"],
  "388": ["Talpa de Allende", "Jalisco"],
  "389": ["Tecuala", "Nayarit"],
  "391": ["Atotonilco El Alto", "Jalisco"],
  "392": ["Ocotlán", "Jalisco"],
  "393": ["La Barca", "Jalisco"],
  "394": ["Cotija de la Paz", "Michoacán"],
  "395": ["San Juan de los Lagos", "Jalisco"],
  "411": ["Cortazar", "Guanajuato"],
  "412": ["Juventino Rosas", "Guanajuato"],
  "413": ["Apaseo el Alto", "Guanajuato"],
  "414": ["Tequisquiapan", "Querétaro"],
  "415": ["San Miguel de Allende", "Guanajuato"],
  "417": ["Acámbaro", "Guanajuato"],
  "418": ["Dolores Hidalgo", "Guanajuato"],
  "419": ["San José Iturbide", "Guanajuato"],
  "421": ["Jerécuaro", "Guanajuato"],
  "422": ["Ario de Rosales", "Michoacán"],
  "423": ["Paracho", "Michoacán"],
  "424": ["Coalcoman", "Michoacán"],
  "425": ["Nueva Italia", "Michoacán"],
  "426": ["Buenavista Tomatlán", "Michoacán"],
  "427": ["San Juan del Río", "Querétaro"],
  "428": ["Ocampo", "Guanajuato"],
  "429": ["Abasolo", "Guanajuato"],
  "431": ["Jalostotitlán", "Jalisco"],
  "432": ["Romita", "Guanajuato"],
  "433": ["Sombrerete", "Zacatecas"],
  "434": ["Pátzcuaro", "Michoacán"],
  "435": ["Huetamo", "Michoacán"],
  "436": ["Zacapu", "Michoacán"],
  "437": ["Tlaltenango", "Zacatecas"],
  "438": ["Puruándiro", "Michoacán"],
  "441": ["Ezequiel Montes", "Querétaro"],
  "442": ["Querétaro", "Querétaro"],
  "443": ["Morelia", "Michoacán"],
  "444": ["San Luis Potosí", "San Luis Potosí"],
  "445": ["Uriangato", "Guanajuato"],
  "447": ["Maravatío", "Michoacán"],
  "448": ["Pedro Escobedo", "Querétaro"],
  "449": ["Aguascalientes", "Aguascalientes"],
  "451": ["Zinapécuaro", "Michoacán"],
  "452": ["Uruapan", "Michoacán"],
  "453": ["Apatzingán", "Michoacán"],
  "454": ["Quiroga", "Michoacán"],
  "455": ["Cuitzeo del Porvenir", "Michoacán"],
  "456": ["Valle de Santiago", "Guanajuato"],
  "457": ["Valparaíso", "Zacatecas"],
  "458": ["San Pedro Piedra Gorda", "Zacatecas"],
  "459": ["Tacámbaro", "Michoacán"],
  "461": ["Celaya", "Guanajuato"],
  "462": ["Irapuato", "Guanajuato"],
  "463": ["Jalpa", "Zacatecas"],
  "464": ["Salamanca", "Guanajuato"],
  "465": ["Pabellón de Arteaga", "Aguascalientes"],
  "466": ["Salvatierra", "Guanajuato"],
  "467": ["García de la Cadena", "Zacatecas"],
  "468": ["San Luis de la Paz", "Guanajuato"],
  "469": ["Pénjamo", "Guanajuato"],
  "471": ["Purépero", "Michoacán"],
  "472": ["Silao", "Guanajuato"],
  "473": ["Guanajuato", "Guanajuato"],
  "474": ["Lagos de Moreno", "Jalisco"],
  "475": ["Encarnación de Díaz", "Jalisco"],
  "476": ["San Francisco del Rincón", "Guanajuato"],
  "477": ["León", "Guanajuato"],
  "478": ["Pozo de Gamboa", "Zacatecas"],
  "481": ["Ciudad Valles", "San Luis Potosí"],
  "482": ["El Naranjo", "San Luis Potosí"],
  "483": ["Tamazunchale", "San Luis Potosí"],
  "485": ["Santa María del Río", "San Luis Potosí"],
  "486": ["Cerritos", "San Luis Potosí"],
  "487": ["Rioverde", "San Luis Potosí"],
  "488": ["Matehuala", "San Luis Potosí"],
  "489": ["Tamuín", "San Luis Potosí"],
  "492": ["Guadalupe", "Zacatecas"],
  "493": ["Fresnillo", "Zacatecas"],
  "494": ["Jerez de García Salinas", "Zacatecas"],
  "495": ["Calvillo", "Aguascalientes"],
  "496": ["Loreto", "Zacatecas"],
  "498": ["Río Grande", "Zacatecas"],
  "499": ["Colotlán", "Jalisco"],
  "588": ["Villa del Carbón", "Estado de México"],
  "591": ["Zumpango", "Estado de México"],
  "592": ["Otumba", "Estado de México"],
  "593": ["Teoloyucan", "Estado de México"],
  "594": ["Tepexpan", "Estado de México"],
  "595": ["Texcoco de Mora", "Estado de México"],
  "596": ["Los Reyes Acozac", "Estado de México"],
  "597": ["Amecameca", "Estado de México"],
  "599": ["Santa María Ajoloapan", "Estado de México"],
  "612": ["La Paz", "Baja California Sur"],
  "613": ["Ciudad Constitución", "Baja California Sur"],
  "614": ["Chihuahua", "Chihuahua"],
  "615": ["San Lucas", "Baja California Sur"],
  "616": ["Colonia Vicente Guerrero", "Baja California"],
  "618": ["Durango", "Durango"],
  "621": ["Saucillo", "Chihuahua"],
  "622": ["Guaymas", "Sonora"],
  "623": ["Pesqueira", "Sonora"],
  "624": ["Cabo San Lucas", "Baja California Sur"],
  "625": ["Ciudad Cuauhtémoc", "Chihuahua"],
  "626": ["Manuel Ojinaga", "Chihuahua"],
  "627": ["Parral", "Chihuahua"],
  "628": ["Santa Bárbara", "Chihuahua"],
  "629": ["Ceballos", "Durango"],
  "631": ["Nogales", "Sonora"],
  "632": ["Magdalena de Kino", "Sonora"],
  "633": ["Agua Prieta", "Sonora"],
  "634": ["Nacozari", "Sonora"],
  "635": ["San Juanito", "Chihuahua"],
  "636": ["Nuevo Casas Grandes", "Chihuahua"],
  "637": ["Caborca", "Sonora"],
  "638": ["Puerto Peñasco", "Sonora"],
  "639": ["Ciudad Delicias", "Chihuahua"],
  "641": ["Santa Ana", "Sonora"],
  "642": ["Navojoa", "Sonora"],
  "643": ["Pueblo Yaqui", "Sonora"],
  "644": ["Ciudad Obregón", "Sonora"],
  "645": ["Cananea", "Sonora"],
  "646": ["Ensenada", "Baja California"],
  "647": ["Huatabampo", "Sonora"],
  "648": ["Ciudad Camargo", "Chihuahua"],
  "649": ["Guachochi", "Chihuahua"],
  "651": ["Sonoita", "Sonora"],
  "652": ["Ciudad Madera", "Chihuahua"],
  "653": ["San Luis Río Colorado", "Sonora"],
  "656": ["Ciudad Juárez", "Chihuahua"],
  "658": ["Guadalupe Victoria", "Baja California"],
  "659": ["Ejido Benito Juárez", "Chihuahua"],
  "661": ["Playas de Rosarito", "Baja California"],
  "662": ["Hermosillo", "Sonora"],
  "664": ["Tijuana", "Baja California"],
  "665": ["Tecate", "Baja California"],
  "667": ["Culiacán", "Sinaloa"],
  "668": ["Los Mochis", "Sinaloa"],
  "669": ["Mazatlán", "Sinaloa"],
  "671": ["Cuencame de Ceniceros", "Durango"],
  "672": ["Navolato", "Sinaloa"],
  "673": ["Guamuchil", "Sinaloa"],
  "674": ["Santiago Papasquiaro", "Durango"],
  "675": ["El Salto", "Durango"],
  "676": ["Guadalupe Victoria", "Durango"],
  "677": ["Canatlán", "Durango"],
  "686": ["Mexicali", "Baja California"],
  "687": ["Guasave", "Sinaloa"],
  "694": ["Rosario", "Sinaloa"],
  "695": ["Escuinapa", "Sinaloa"],
  "696": ["La Cruz", "Sinaloa"],
  "697": ["La Reforma", "Sinaloa"],
  "698": ["El Fuerte", "Sinaloa"],
  "711": ["El Oro", "Estado de México"],
  "712": ["Atlacomulco", "Estado de México"],
  "713": ["Xalatlaco", "Estado de México"],
  "714": ["San Miguel", "Estado de México"],
  "715": ["Zitacuaro", "Michoacán"],
  "716": ["San Simón", "Estado de México"],
  "717": ["Tenango de Arista", "Estado de México"],
  "718": ["Temascalcingo", "Estado de México"],
  "719": ["San Francisco Xonacatlán", "Estado de México"],
  "721": ["Ixtapan de la Sal", "Estado de México"],
  "722": ["Toluca", "Estado de México"],
  "723": ["Coatepec Harinas", "Estado de México"],
  "724": ["Tejupilco de Hidalgo", "Estado de México"],
  "725": ["San Francisco Tlalcilalcalpan", "Estado de México"],
  "726": ["Valle de Bravo", "Estado de México"],
  "727": ["Huitzuco", "Guerrero"],
  "728": ["San Mateo Atenco", "Estado de México"],
  "731": ["Yecapixtla", "Morelos"],
  "732": ["Arcelia", "Guerrero"],
  "733": ["Iguala", "Guerrero"],
  "734": ["Zacatepec de Hidalgo", "Morelos"],
  "735": ["Cuautla", "Morelos"],
  "736": ["Teloloapan", "Guerrero"],
  "737": ["Coatetelco", "Morelos"],
  "738": ["Mixquiahuala", "Hidalgo"],
  "739": ["Tepoztlán", "Morelos"],
  "741": ["Ometepec", "Guerrero"],
  "742": ["Atoyac de Álvarez", "Guerrero"],
  "743": ["San Agustín Tlaxiaca", "Hidalgo"],
  "744": ["Acapulco", "Guerrero"],
  "745": ["Cuautepec", "Hidalgo"],
  "746": ["Benito Juárez", "Veracruz"],
  "747": ["Chilpancingo", "Guerrero"],
  "748": ["Apan", "Hidalgo"],
  "749": ["Calpulalpan", "Tlaxcala"],
  "751": ["Puente de Ixtla", "Morelos"],
  "753": ["Ciudad Lázaro Cárdenas", "Michoacán"],
  "754": ["Tixtla", "Guerrero"],
  "755": ["Ixtapa Zihuatanejo", "Guerrero"],
  "756": ["Chilapa", "Guerrero"],
  "757": ["Tlapa de Comonfort", "Guerrero"],
  "758": ["Petatlán", "Guerrero"],
  "759": ["Ixmiquilpan", "Hidalgo"],
  "761": ["Jilotepec", "Estado de México"],
  "762": ["Taxco", "Guerrero"],
  "763": ["Tlahuelilpan", "Hidalgo"],
  "764": ["Xicotepec de Juárez", "Puebla"],
  "765": ["Potrero del Llano", "Veracruz"],
  "766": ["Gutiérrez Zamora", "Veracruz"],
  "767": ["Ciudad Altamirano", "Guerrero"],
  "768": ["Naranjos", "Veracruz"],
  "769": ["Axochiapan", "Morelos"],
  "771": ["Pachuca de Soto", "Hidalgo"],
  "772": ["Actopan", "Hidalgo"],
  "773": ["Tepeji de Ocampo", "Hidalgo"],
  "774": ["Zacualtipán", "Hidalgo"],
  "775": ["Tulancingo", "Hidalgo"],
  "776": ["Huauchinango", "Puebla"],
  "777": ["Cuernavaca", "Morelos"],
  "778": ["Tlaxcoapan", "Hidalgo"],
  "779": ["Tizayuca", "Hidalgo"],
  "781": ["Coyuca de Benítez", "Guerrero"],
  "782": ["Poza Rica", "Veracruz"],
  "783": ["Tuxpan", "Veracruz"],
  "784": ["Papantla", "Veracruz"],
  "785": ["Cerro Azul", "Veracruz"],
  "786": ["Melchor Ocampo", "Michoacán"],
  "789": ["Huejutla de Reyes", "Hidalgo"],
  "791": ["Ciudad Sahagún", "Hidalgo"],
  "797": ["Zacatlán", "Puebla"],
  "821": ["Guadalupe", "Nuevo León"],
  "823": ["China", "Nuevo León"],
  "824": ["Sabinas Hidalgo", "Nuevo León"],
  "825": ["Ciénaga de Flores", "Nuevo León"],
  "826": ["Montemorelos", "Nuevo León"],
  "828": ["Cadereyta", "Nuevo León"],
  "829": ["Hidalgo", "Nuevo León"],
  "831": ["Ciudad Mante", "Tamaulipas"],
  "832": ["Tula", "Tamaulipas"],
  "833": ["Tampico", "Tamaulipas"],
  "834": ["Ciudad Victoria", "Tamaulipas"],
  "835": ["Soto la Marina", "Tamaulipas"],
  "836": ["Estación Manuel", "Tamaulipas"],
  "841": ["San Fernando", "Tamaulipas"],
  "842": ["Parras de la Fuente", "Coahuila"],
  "844": ["Saltillo", "Coahuila"],
  "845": ["Ebano", "San Luis Potosí"],
  "846": ["Pánuco", "Veracruz"],
  "861": ["Sabinas", "Coahuila"],
  "862": ["Nava", "Coahuila"],
  "864": ["Muzquiz", "Coahuila"],
  "866": ["Monclova", "Coahuila"],
  "867": ["Nuevo Laredo", "Tamaulipas"],
  "868": ["Matamoros", "Tamaulipas"],
  "869": ["San Buenaventura", "Coahuila"],
  "871": ["Torreón", "Coahuila"],
  "872": ["San Pedro", "Coahuila"],
  "873": ["Ciudad Anáhuac", "Nuevo León"],
  "877": ["Ciudad Acuña", "Coahuila"],
  "878": ["Piedras Negras", "Coahuila"],
  "891": ["Gustavo Díaz Ordaz", "Tamaulipas"],
  "892": ["Cerralvo", "Nuevo León"],
  "894": ["Valle Hermoso", "Tamaulipas"],
  "897": ["Ciudad Miguel Alemán", "Tamaulipas"],
  "899": ["Reynosa", "Tamaulipas"],
  "913": ["Frontera", "Tabasco"],
  "914": ["Cunduacán", "Tabasco"],
  "916": ["Palenque", "Chiapas"],
  "917": ["Huimanguillo", "Tabasco"],
  "918": ["Pijijiapan", "Chiapas"],
  "919": ["Ocosingo", "Chiapas"],
  "921": ["Coatzacoalcos", "Veracruz"],
  "922": ["Minatitlán", "Veracruz"],
  "923": ["Las Choapas", "Veracruz"],
  "924": ["Acayucan", "Veracruz"],
  "932": ["Teapa", "Tabasco"],
  "933": ["Paraíso", "Tabasco"],
  "934": ["Tenosique", "Tabasco"],
  "936": ["Macuspana", "Tabasco"],
  "937": ["Cárdenas", "Tabasco"],
  "938": ["Ciudad del Carmen", "Campeche"],
  "951": ["Oaxaca de Juárez", "Oaxaca"],
  "953": ["Santa Cruz", "Oaxaca"],
  "954": ["Puerto Escondido", "Oaxaca"],
  "958": ["San Pedro Pochutla", "Oaxaca"],
  "961": ["Tuxtla Gutiérrez", "Chiapas"],
  "962": ["Tapachula", "Chiapas"],
  "963": ["Comitán de Domínguez", "Chiapas"],
  "964": ["Huixtla", "Chiapas"],
  "965": ["El Parral", "Chiapas"],
  "966": ["Tonalá", "Chiapas"],
  "967": ["San Cristóbal de las Casas", "Chiapas"],
  "968": ["Cintalapa", "Chiapas"],
  "969": ["Progreso", "Yucatán"],
  "971": ["Juchitán", "Oaxaca"],
  "972": ["Matías Romero", "Oaxaca"],
  "981": ["Campeche", "Campeche"],
  "982": ["Champotón", "Campeche"],
  "983": ["Chetumal", "Quintana Roo"],
  "984": ["Playa del Carmen", "Quintana Roo"],
  "985": ["Valladolid", "Yucatán"],
  "986": ["Tizimín", "Yucatán"],
  "987": ["Cozumel", "Quintana Roo"],
  "988": ["Uman", "Yucatán"],
  "991": ["Motul", "Yucatán"],
  "992": ["Teopisca", "Chiapas"],
  "993": ["Villahermosa", "Tabasco"],
  "994": ["Chahuites", "Oaxaca"],
  "995": ["Magdalena Tequisistlán", "Oaxaca"],
  "996": ["Calkini", "Campeche"],
  "997": ["Ticul", "Yucatán"],
  "998": ["Cancún", "Quintana Roo"],
  "999": ["Mérida", "Yucatán"],
};

/** Devuelve { lada, ciudad, estado } a partir de un teléfono mexicano, o null. */
export function ladaInfo(phone: string | null | undefined) {
  if (!phone) return null;
  let d = phone.replace(/\D/g, "");
  if (d.length === 13 && d.startsWith("521")) d = d.slice(3);
  else if (d.length === 12 && d.startsWith("52")) d = d.slice(2);
  if (d.length !== 10) return null;
  const two = d.slice(0, 2);
  const lada = LADAS[two] ? two : d.slice(0, 3);
  const hit = LADAS[lada];
  if (!hit) return null;
  return { lada, ciudad: hit[0], estado: hit[1] };
}
